### ISSUE TITLE
api to close the tree view

### ISSUE THREAD

**Issue by prabirshrestha** [m-pilia/vim-yggdrasil#16]
Currently I'm using `bwipeout`. Can you officially document what we should use?

**Comment by m-pilia** [comment]
Hi! Yes, wiping the buffer should be the way to go. Good point, I added some documentation and an API method to wipe the tree in #17 (I guess it could be useful to have it in the future, if further cleanup will be required besides wiping the buffer).

**Comment by m-pilia** [comment]
Almost forgot to mention, since the tree view buffer has [bufhidden=wipe](https://github.com/m-pilia/vim-yggdrasil/blob/1a61099/autoload/yggdrasil/tree.vim#L214), closing the window or tab is also enough to wipe the buffer.
