### ISSUE TITLE
installation improvements

### ISSUE THREAD

**Issue by prabirshrestha** [m-pilia/vim-yggdrasil#18]
We now use this in [vim-lsp](https://github.com/prabirshrestha/vim-lsp). And here are some improvements I can think of.

* Format the LICENSE file so we can easily copy paste it. https://github.com/prabirshrestha/vim-lsp/blob/c35a3287743a5ef1a15116dae8705419a5bfd830/LICENSE-THIRD-PARTY
* Include repo link in the embeded file. This is because I do want to give you credits for writing this so other looking at the vim-lsp codebase will discover it.
* Include license link in the embed file
* Include the command that I used to install in the embeded file so I can copy paste and use the same command to update it later without me adding notes somewhere else
* Currently it always generates `yggdrasil` folder but I want it to be saved as `lsp#utils#tree#new()`.
* I had to manually update the `<Plug>` mappings to prefix with `lsp` so that it looks like `<Plug>(lsp-tree-toggle-node)`. 
* Same for buffer variables. I would like to prefix with `lsp` - `b:lsp_tree.set_collapsed_under_cursor`
* Same for syntax variables. `LspTreeMarkLeaf`.
* Same for filetype. `lsp-tree`.

Primary reason for prefixing with `lsp-` is that I can then have update the vim-lsp documentations.

Overall I found it very easy to use the api the file was small enough to make some of the above minor changes. Thanks for the awesome plugin. Saved a ton of my time so I can focus on consuming it instead of building it from scratch.

**Comment by m-pilia** [comment]
Hi, thanks for the feedback! I am definitely going to implement your suggestions.

**Comment by prabirshrestha** [comment]
also would be good to put the git sha in embeded file if `executable('git')` exists that way we now which version it is.
